CREATE TABLE IF NOT EXISTS `CUSTOMERS` (

    `ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `FIRST_NAME` varchar(20),
    `LAST_NAME` varchar(50),
    `BIRTH_DATE` date

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;